matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

script:
  - cd ${TRAVIS_BUILD_DIR}
  - pwd
  - ls -al
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - ctest